CC=avr-gcc
CFLAGS=-mmcu=atmega128 -c -Wall -DTINYOS -DATRON
AR=avr-ar


TARGETSOURCE=\
targets/atron/atron-tos/tos-api/AbstractAtronTosApi.c \
targets/atron/atron-tos/tos-api/AtronTosApi.c \
control/behaviors/atron/self-reconfiguration/SnakeToQuadruped_8M/SnakeToQuadruped_8M.c \
control/behaviors/atron/self-reconfiguration/QuadrupedToSnake_8M/QuadrupedToSnake_8M.c \
control/behaviors/atron/locomotion/QuadrupedGait_8M/QuadrupedGait_8M.c \
control/behaviors/atron/locomotion/SnakeGait/SnakeGait.c \
tools/atron/AtronStatus/AtronStatus.c
