CC=gcc
CFLAGS=-c -Wall -DDYNAMIXEL -DD2U
AR=ar

TARGETINCLUDE = -I../extlib/ftd2xx

TARGETSOURCE=\
targets/dynamixel/dynamixel-d2u/dxl_hal.c \
targets/dynamixel/dynamixel-d2u/dynamixel.c \
targets/dynamixel/dynamixel-d2u/AbstractDynamixelApi.c \
targets/utils/socket-tools/SimpleSocket.c \
targets/dynamixel/dynamixel-d2u/DynamixelD2UApi.c 

